/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadhondt;

/**
 *
 * @author Elia
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblMenu = new javax.swing.JLabel();
        BtnCargarDatos = new javax.swing.JButton();
        BtnModificarDatos = new javax.swing.JButton();
        BtnBajaPartido = new javax.swing.JButton();
        BtnInfCargos = new javax.swing.JButton();
        BtnInfDivision = new javax.swing.JButton();
        BtnInfPartidos = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(439, 390));

        LblMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblMenu.setText("Menú Principal");

        BtnCargarDatos.setText("Cargar datos de partido político");
        BtnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarDatosActionPerformed(evt);
            }
        });

        BtnModificarDatos.setText("Modificar datos de un partido político");
        BtnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarDatosActionPerformed(evt);
            }
        });

        BtnBajaPartido.setText("Dar de baja partido político");
        BtnBajaPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBajaPartidoActionPerformed(evt);
            }
        });

        BtnInfCargos.setText("Informe sobre cargos a cubrir");
        BtnInfCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfCargosActionPerformed(evt);
            }
        });

        BtnInfDivision.setText("Informe sobre división de votos");
        BtnInfDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfDivisionActionPerformed(evt);
            }
        });

        BtnInfPartidos.setText("Informe sobre partidos políticos");
        BtnInfPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfPartidosActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset - Condiciones iniciales (Borra todos los datos)");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCargarDatos)
                    .addComponent(BtnModificarDatos)
                    .addComponent(BtnBajaPartido)
                    .addComponent(BtnInfCargos)
                    .addComponent(BtnInfDivision)
                    .addComponent(BtnInfPartidos)
                    .addComponent(BtnReset))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCargarDatos)
                .addGap(20, 20, 20)
                .addComponent(BtnModificarDatos)
                .addGap(18, 18, 18)
                .addComponent(BtnBajaPartido)
                .addGap(18, 18, 18)
                .addComponent(BtnInfCargos)
                .addGap(18, 18, 18)
                .addComponent(BtnInfDivision)
                .addGap(18, 18, 18)
                .addComponent(BtnInfPartidos)
                .addGap(18, 18, 18)
                .addComponent(BtnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarDatosActionPerformed
        new CargarDatos().setVisible(true);
    }//GEN-LAST:event_BtnCargarDatosActionPerformed

    private void BtnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarDatosActionPerformed
        new ModificarDatos().setVisible(true);
    }//GEN-LAST:event_BtnModificarDatosActionPerformed

    private void BtnBajaPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBajaPartidoActionPerformed
        new BajaPartido().setVisible(true);
    }//GEN-LAST:event_BtnBajaPartidoActionPerformed

    private void BtnInfCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfCargosActionPerformed
        new InformeCargos().setVisible(true);
    }//GEN-LAST:event_BtnInfCargosActionPerformed

    private void BtnInfDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfDivisionActionPerformed
        new InformeDivision().setVisible(true);
    }//GEN-LAST:event_BtnInfDivisionActionPerformed

    private void BtnInfPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfPartidosActionPerformed
        new InformePartidos().setVisible(true);
    }//GEN-LAST:event_BtnInfPartidosActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed

    }//GEN-LAST:event_BtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBajaPartido;
    private javax.swing.JButton BtnCargarDatos;
    private javax.swing.JButton BtnInfCargos;
    private javax.swing.JButton BtnInfDivision;
    private javax.swing.JButton BtnInfPartidos;
    private javax.swing.JButton BtnModificarDatos;
    private javax.swing.JButton BtnReset;
    private javax.swing.JLabel LblMenu;
    // End of variables declaration//GEN-END:variables
}
