package vista;

import dao.Conexion;
import dao.SistemaDAO;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

public class MainB extends javax.swing.JFrame {

    
    CardLayout cl;
    public MainB() {
        initComponents();
        pnlPrincipal.setLayout(new CardLayout());
        cl = (CardLayout)(pnlPrincipal.getLayout());
        pnlPrincipal.add(new PanelFormulario1(), "crear");
        pnlPrincipal.add(new PanelFormulario2(), "modificar");
        pnlPrincipal.add(new PanelFormulario3(), "eliminar");
        pnlPrincipal.add(new PanelFormulario4(), "cargos");
    }
    
    /**
    * Compila y ejecuta un informe JasperReports desde la ruta indicada,
    * conectándose a la base de datos para obtener los datos, y lo muestra
    * en una ventana separada con el visor de JasperReports.
    * @param ruta ruta del archivo .jrxml dentro del classpath, ej: "/informes/informe.jrxml"
    */
    private void irAlInforme(String ruta){
        try {
            // Carga el archivo de diseño del informe desde el classpath
            java.io.InputStream jrxml = getClass().getResourceAsStream(ruta);
            // Compila el .jrxml a un objeto JasperReport ejecutable
            net.sf.jasperreports.engine.JasperReport jasperReport =
                net.sf.jasperreports.engine.JasperCompileManager.compileReport(jrxml);
            java.util.Map<String, Object> parametros = new java.util.HashMap<>();
            
            // Ejecuta el informe contra la base de datos y genera el resultado
            JasperPrint jasperPrint =
                JasperFillManager.fillReport(
                    jasperReport,
                    parametros,
                    Conexion.conectar()
                );
            
            // Se encargar de mostrar el informe generado en pantalla
            JRViewer viewer = new JRViewer(jasperPrint);
            pnlPrincipal.removeAll();
            pnlPrincipal.add(viewer);
            pnlPrincipal.revalidate();
            pnlPrincipal.repaint();
            
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error al generar el informe: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        mnArchivos = new javax.swing.JMenu();
        mnitCrear = new javax.swing.JMenuItem();
        mnitEliminar = new javax.swing.JMenuItem();
        sprSeparador = new javax.swing.JPopupMenu.Separator();
        mnitSalir = new javax.swing.JMenuItem();
        mnEditar = new javax.swing.JMenu();
        mnitModificar = new javax.swing.JMenuItem();
        mnitReset = new javax.swing.JMenuItem();
        mnInformes = new javax.swing.JMenu();
        mnitInformeCargos = new javax.swing.JMenuItem();
        mnuitDivisionVotos = new javax.swing.JMenuItem();
        mnitPartidos = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlPrincipal.setMinimumSize(new java.awt.Dimension(200, 200));
        pnlPrincipal.setPreferredSize(null);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        menuBar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        mnArchivos.setText("Archivos");
        mnArchivos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        mnitCrear.setText("Cargar partido");
        mnitCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitCrearActionPerformed(evt);
            }
        });
        mnArchivos.add(mnitCrear);

        mnitEliminar.setText("Eliminar partido");
        mnitEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitEliminarActionPerformed(evt);
            }
        });
        mnArchivos.add(mnitEliminar);
        mnArchivos.add(sprSeparador);

        mnitSalir.setText("Salir");
        mnitSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitSalirActionPerformed(evt);
            }
        });
        mnArchivos.add(mnitSalir);

        menuBar.add(mnArchivos);

        mnEditar.setText("Editar");
        mnEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        mnitModificar.setText("Modificar partido");
        mnitModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitModificarActionPerformed(evt);
            }
        });
        mnEditar.add(mnitModificar);

        mnitReset.setText("Reiniciar datos");
        mnitReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitResetActionPerformed(evt);
            }
        });
        mnEditar.add(mnitReset);

        menuBar.add(mnEditar);

        mnInformes.setText("Informes");
        mnInformes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        mnitInformeCargos.setText("Cargos a cubrir");
        mnitInformeCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitInformeCargosActionPerformed(evt);
            }
        });
        mnInformes.add(mnitInformeCargos);

        mnuitDivisionVotos.setText("División de votos");
        mnuitDivisionVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitDivisionVotosActionPerformed(evt);
            }
        });
        mnInformes.add(mnuitDivisionVotos);

        mnitPartidos.setText("Partidos políticos");
        mnitPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitPartidosActionPerformed(evt);
            }
        });
        mnInformes.add(mnitPartidos);

        menuBar.add(mnInformes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Navega al panel de creación de partidos.
    */
    private void mnitCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitCrearActionPerformed
        cl.show(pnlPrincipal, "crear");
    }//GEN-LAST:event_mnitCrearActionPerformed

    /**
    * Navega al panel de eliminación de partidos.
    */
    private void mnitEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitEliminarActionPerformed
        cl.show(pnlPrincipal, "eliminar");
    }//GEN-LAST:event_mnitEliminarActionPerformed

    /**
    * Navega al panel de modificación de partidos.
    */
    private void mnitModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitModificarActionPerformed
        cl.show(pnlPrincipal, "modificar");
    }//GEN-LAST:event_mnitModificarActionPerformed

    /**
    * Cierra la aplicación.
    */
    private void mnitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnitSalirActionPerformed

    /**
    * Navega al panel de cálculo de cargos e informe D'Hondt.
    */
    private void mnitInformeCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitInformeCargosActionPerformed
        cl.show(pnlPrincipal, "cargos");
    }//GEN-LAST:event_mnitInformeCargosActionPerformed
    
    /**
     * Genera y muestra el informe de división de votos.
     */
    private void mnuitDivisionVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitDivisionVotosActionPerformed
        irAlInforme("/informes/informeDivisionVotos.jrxml");
    }//GEN-LAST:event_mnuitDivisionVotosActionPerformed

    /**
    * Genera y muestra el informe de partidos políticos.
    */
    private void mnitPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitPartidosActionPerformed
        irAlInforme("/informes/informePartidos.jrxml");
    }//GEN-LAST:event_mnitPartidosActionPerformed
    
    /**
    * Elimina todos los datos de las tablas de resultados y partidos,
    * reseteando el sistema a su estado inicial.
    */
    private void mnitResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitResetActionPerformed
        SistemaDAO.eliminarDatos();
    }//GEN-LAST:event_mnitResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainB().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnArchivos;
    private javax.swing.JMenu mnEditar;
    private javax.swing.JMenu mnInformes;
    private javax.swing.JMenuItem mnitCrear;
    private javax.swing.JMenuItem mnitEliminar;
    private javax.swing.JMenuItem mnitInformeCargos;
    private javax.swing.JMenuItem mnitModificar;
    private javax.swing.JMenuItem mnitPartidos;
    private javax.swing.JMenuItem mnitReset;
    private javax.swing.JMenuItem mnitSalir;
    private javax.swing.JMenuItem mnuitDivisionVotos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPopupMenu.Separator sprSeparador;
    // End of variables declaration//GEN-END:variables

}
