package vista;

import modelo.ResultadoVotos;
import modelo.Partido;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import dao.Conexion;
import dao.ResultadoVotosDAO;
import servicios.DhondtService;
import servicios.PartidoService;

public class PanelFormulario4 extends javax.swing.JPanel {
    
    DefaultComboBoxModel model;
    public PanelFormulario4() {
        initComponents();
        cargarDatosIniciales();
        pnlInforme.setVisible(false);
    }
    
    /**
    * Sobrescribe setVisible para reiniciar el panel cada vez que se abre,
    * asegurando que los controles estén en su estado inicial.
    */
    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag) {
            cargarDatosIniciales();
        }
    }
    
    /**
    * Inicializa los controles del panel: carga las opciones de porcentaje
    * del 1% al 100% en el combo box y limpia el campo de cargos.
    */
    private void cargarDatosIniciales(){
        model = new DefaultComboBoxModel();
        for (int i=1; i <= 100; i++){
            model.addElement(i+"%");
        }
        
        cbxPorcentaje.setModel(model);
        ftxtCargos.setText("");
    }
    
    /**
    * Compila y ejecuta el informe de cargos contra la base de datos,
    * luego lo muestra dentro del panel usando mostrarInforme().
    */
    protected void irAlInforme(){
        try {
            // Carga el archivo de diseño del informe desde el classpath
            java.io.InputStream jrxml = getClass().getResourceAsStream("/informes/informeCargos.jrxml");
            // Compila el .jrxml a un objeto JasperReport ejecutable
            net.sf.jasperreports.engine.JasperReport jasperReport =
                net.sf.jasperreports.engine.JasperCompileManager.compileReport(jrxml);
            java.util.Map<String, Object> parametros = new java.util.HashMap<>();
            
            // Ejecuta el informe contra la base de datos y genera el resultado
            JasperPrint jasperPrint =
                JasperFillManager.fillReport(
                    jasperReport,
                    parametros,
                    Conexion.conectar()
                );
            
            mostrarInforme(jasperPrint);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error al generar el informe: " + e.getMessage());
        }
    }
    
    /**
    * Muestra el informe generado dentro de pnlInforme usando un JRViewer.
    * Agrega un botón "Volver" en la parte superior para regresar a los controles.
    * Oculta pnlCargos y hace visible pnlInforme.
    */
    private void mostrarInforme(JasperPrint jasperPrint){
        JRViewer viewer = new JRViewer(jasperPrint);
        
        // Panel contenedor del botón para limitar su tamaño
        javax.swing.JPanel pnlVolver = new javax.swing.JPanel();
        javax.swing.JButton btnVolver = new javax.swing.JButton("Volver");
        btnVolver.setMaximumSize(new java.awt.Dimension(300, 30));
        btnVolver.setPreferredSize(new java.awt.Dimension(300, 30));
        btnVolver.addActionListener(e -> {
            pnlInforme.setVisible(false); // oculta el informe
            pnlCargos.setVisible(true); // muestra los controles nuevamente
        });
        pnlVolver.add(btnVolver);
        
        pnlInforme.removeAll();
        pnlInforme.setLayout(new BorderLayout());
        pnlInforme.add(pnlVolver, BorderLayout.NORTH);
        pnlInforme.add(viewer, BorderLayout.CENTER);
        pnlInforme.revalidate();
        pnlInforme.repaint();
        
        pnlCargos.setVisible(false); // oculta los controles
        pnlInforme.setVisible(true); // muestra el informe
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCargos = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        cbxPorcentaje = new javax.swing.JComboBox<>();
        lblPorcentaje = new javax.swing.JLabel();
        ftxtCargos = new javax.swing.JFormattedTextField();
        lblCantidadCargos = new javax.swing.JLabel();
        pnlInforme = new javax.swing.JPanel();

        btnAceptar.setText("Aceptar");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAceptarKeyPressed(evt);
            }
        });

        lblPorcentaje.setText("Indique porcentaje");

        ftxtCargos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        ftxtCargos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtCargos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxtCargosKeyTyped(evt);
            }
        });

        lblCantidadCargos.setText("Cantidad de cargos a cubrir");

        javax.swing.GroupLayout pnlCargosLayout = new javax.swing.GroupLayout(pnlCargos);
        pnlCargos.setLayout(pnlCargosLayout);
        pnlCargosLayout.setHorizontalGroup(
            pnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCargosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCargosLayout.createSequentialGroup()
                        .addGroup(pnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCantidadCargos)
                            .addComponent(ftxtCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPorcentaje)
                            .addGroup(pnlCargosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cbxPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCargosLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnAceptar)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlCargosLayout.setVerticalGroup(
            pnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCargosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadCargos)
                    .addComponent(lblPorcentaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInforme.setLayout(new java.awt.BorderLayout(getWidth(), getHeight()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 385, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Ejecuta el cálculo D'Hondt con los parámetros ingresados, guarda los
    * resultados en la base de datos y muestra el informe de cargos.
    */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        List<Partido> todosLosPartidos = PartidoService.obtenerPartidos();
        if (todosLosPartidos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay partidos cargados.");
            return;
        }
        // Suma de votos de todos los partidos, usado como base para los porcentajes
        int totalVotos = todosLosPartidos.stream().mapToInt(Partido::getVotos).sum();
        String porcentaje = cbxPorcentaje.getSelectedItem().toString();
        
        // Filtra los partidos que superan el umbral del porcentaje seleccionado
        List<Partido> partidos = DhondtService.filtrarPartidos(todosLosPartidos, porcentaje);
        if (partidos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay partidos que superen el porcentaje.");
            return;
        }

        String cargosPrev = ftxtCargos.getText();
        if (cargosPrev.isEmpty() || cargosPrev.equals("0")) {
            JOptionPane.showMessageDialog(null, "No se asignó una cantidad de cargos.");
            return;
        }

        int cargos = Integer.parseInt(cargosPrev);
        // Calcula todos los cocientes D'Hondt y los ordena de mayor a menor
        List<ResultadoVotos> cocientes = DhondtService.calcularCocientes(partidos, totalVotos, cargos);
        // Obtiene solo los primeros N cocientes que ocupan cargo
        List<ResultadoVotos> resultados = DhondtService.obtenerResultados(cocientes, cargos);
        
        ResultadoVotosDAO.insertarResultados(resultados);
        // Guarda la tabla completa de división de votos para el segundo informe
        DhondtService.guardarDivisionVotos(cargos, todosLosPartidos, partidos, cocientes, resultados);
        
        irAlInforme();
    }//GEN-LAST:event_btnAceptarActionPerformed
    
    /**
    * Permite solo dígitos numéricos en el campo de cargos.
    */
    private void ftxtCargosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtCargosKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_ftxtCargosKeyTyped
    
    /**
    * Permite confirmar el formulario presionando Enter
    * como alternativa al click del botón Aceptar.
    */
    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAceptarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             btnAceptar.doClick();
        }
    }//GEN-LAST:event_btnAceptarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cbxPorcentaje;
    private javax.swing.JFormattedTextField ftxtCargos;
    private javax.swing.JLabel lblCantidadCargos;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JPanel pnlCargos;
    private javax.swing.JPanel pnlInforme;
    // End of variables declaration//GEN-END:variables
}
