package vista;

import modelo.Partido;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import servicios.PartidoService;

public class PanelFormulario2 extends javax.swing.JPanel {

    private List<Partido> lista, partidos, partidosFiltrados;
    private int indice = 0;
    
    public PanelFormulario2() {
        initComponents();
        cargarDatosIniciales();
    }
    
    /**
    * Sobrescribe setVisible para recargar los datos cada vez que el panel
    * se hace visible con tal de que siempre muestre información actualizada.
    */
    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag) {
            cargarDatosIniciales();
        }
    }
    
    /**
    * Inicializa el panel obteniendo la lista de partidos desde la base de datos.
    * Si hay partidos, muestra el primero; si no, limpia los campos y avisa al usuario.
    */
    private void cargarDatosIniciales() {
        partidos = PartidoService.obtenerPartidos(); // consulta a la base de datos
        lista = partidos; // lista activa apunta a todos los partidos por defecto
        indice = 0; // siempre empieza desde el primer elemento

        if (!partidos.isEmpty()) {
            mostrarActual();
        } else {
            limpiarCampos();
        }
    }
    
    
    /**
    * Muestra en los campos de texto el partido en la posición actual del índice.
    * Si la lista está vacía, limpia los campos.
    */
    private void mostrarActual() {
        if (lista.isEmpty()) {
            limpiarCampos();
            return;
        }

        Partido p = lista.get(indice);
        
        this.txtNombre.setText(p.getNombre());
        ftxtVotos.setValue((long) p.getVotos()); // setValue respeta el formato numérico

        lblGuia.setText((indice + 1) + " / " + lista.size()); // ej: "2 / 5"
    }
    
    /**
    * Vacía los campos de texto y restablece el indicador de posición a "0 / 0".
    */
    private void limpiarCampos(){
        txtNombre.setText("");
        ftxtVotos.setText("");
        lblGuia.setText("0 / 0");
    }
    
    
    /**
    * Guarda los cambios del partido actualmente mostrado en la base de datos.
    * Si se está usando un filtro, lo reaaplica tras la actualización para mantener
    * la vista filtrada. Si no hay filtro activo, recarga la lista completa.
    */
    private void actualizarPartidoActual() {
        if (lista.isEmpty()) return;

        try {
            Partido p = lista.get(indice);
            String nuevoNombre = txtNombre.getText();
            
            ftxtVotos.commitEdit(); // fuerza el commit del valor antes de leerlo
            
            // Si el valor es null (campo vacío), usa 0 como valor por defecto
            long nuevosVotos = ftxtVotos.getValue() != null ? (Long) ftxtVotos.getValue() : 0;
            
            PartidoService.actualizarPartido(p.getId(), nuevoNombre, nuevosVotos);
            
            partidos = PartidoService.obtenerPartidos(); // recarga la lista actualizada
            
            if(lista == partidosFiltrados && !txtFiltro.getText().isEmpty()){
                // Si hay filtro activo, se actualiza la lista con el filtro
                partidosFiltrados = PartidoService.filtrar(partidos, txtFiltro.getText());
                lista = partidosFiltrados;
                indice = 0;
            } else {
                lista =  partidos;
            }
            
            mostrarActual();
            
            JOptionPane.showMessageDialog(null, "Actualizado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
    * Dispara la actualización del partido cuando el usuario presiona Enter
    * en cualquiera de los campos de texto.
    */
    private void actualizarRegistro(java.awt.event.KeyEvent evt){
        try {
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                actualizarPartidoActual();
            }
        } catch (HeadlessException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblVotos = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        btnPosterior = new javax.swing.JButton();
        btnFin = new javax.swing.JButton();
        btnPrincipio = new javax.swing.JButton();
        lblGuia = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        ftxtVotos = new javax.swing.JFormattedTextField();
        btnBorrarFiltro = new javax.swing.JButton();
        lblFiltro = new javax.swing.JLabel();

        lblNombre.setText("Nombre del partido");
        lblNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNombreMouseClicked(evt);
            }
        });

        lblVotos.setText("Cantidad de votos");
        lblVotos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVotosMouseClicked(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnPosterior.setText(">");
        btnPosterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosteriorActionPerformed(evt);
            }
        });

        btnFin.setText(">|");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });

        btnPrincipio.setText("|<");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });

        lblGuia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuia.setText("0/0");

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        ftxtVotos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        ftxtVotos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtVotos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftxtVotosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxtVotosKeyTyped(evt);
            }
        });

        btnBorrarFiltro.setText("Borrar filtro");
        btnBorrarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarFiltroActionPerformed(evt);
            }
        });

        lblFiltro.setText("Filtro");
        lblFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFiltroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblVotos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(ftxtVotos)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnPrincipio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGuia, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPosterior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFiltro)
                            .addComponent(btnBorrarFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVotos)
                    .addComponent(ftxtVotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnPosterior)
                    .addComponent(btnFin)
                    .addComponent(btnPrincipio)
                    .addComponent(lblGuia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    * Retrocede al partido anterior en la lista si no está en el primero.
    */
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (indice > 0) {
            indice--;
        }
        mostrarActual();
    }//GEN-LAST:event_btnAnteriorActionPerformed
    
    /**
    * Vuelve al primer partido de la lista.
    */
    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        indice = 0;
        mostrarActual();
    }//GEN-LAST:event_btnPrincipioActionPerformed
    
    /**
    * Avanza al partido siguiente en la lista si no está en el último.
    */
    private void btnPosteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosteriorActionPerformed
        if (indice < lista.size()-1) {
            indice++;
        }
        mostrarActual();
    }//GEN-LAST:event_btnPosteriorActionPerformed
    
    /**
    * Salta directamente al último partido de la lista.
    */
    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        indice = lista.size() - 1;
        mostrarActual();
    }//GEN-LAST:event_btnFinActionPerformed
    
    /**
    * Filtra la lista de partidos en tiempo real mientras el usuario escribe.
    * Si el campo de filtro está vacío, muestra todos los partidos.
    */
    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased

        String texto = txtFiltro.getText();
        partidosFiltrados = PartidoService.filtrar(partidos, texto);
        lista = texto.isEmpty() ? partidos : partidosFiltrados;
        
        indice = 0;
        
        mostrarActual();
    }//GEN-LAST:event_txtFiltroKeyReleased
    
    /**
    * Dispara la actualización al presionar Enter en el campo de votos.
    */
    private void ftxtVotosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtVotosKeyPressed
        actualizarRegistro(evt);
    }//GEN-LAST:event_ftxtVotosKeyPressed

    /**
    * Dispara la actualización al presionar Enter en el campo de nombre.
    */
    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        actualizarRegistro(evt);
    }//GEN-LAST:event_txtNombreKeyPressed
    
    /**
    * Permite solo dígitos numéricos en el campo de votos.
    */
    private void ftxtVotosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtVotosKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_ftxtVotosKeyTyped
    
    /**
    * Limpia el campo de filtro para mostrar todos los partidos nuevamente.
    */
    private void btnBorrarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarFiltroActionPerformed
        txtFiltro.setText("");
    }//GEN-LAST:event_btnBorrarFiltroActionPerformed
    
    /**
    * Redirige el foco al campo de nombre al hacer click en su etiqueta.
    */
    private void lblNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreMouseClicked
        txtNombre.requestFocus();
    }//GEN-LAST:event_lblNombreMouseClicked
    
    /**
    * Redirige el foco al campo de votos al hacer click en su etiqueta.
    */
    private void lblVotosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVotosMouseClicked
        ftxtVotos.requestFocus();
    }//GEN-LAST:event_lblVotosMouseClicked

    /**
    * Redirige el foco al campo de filtro al hacer click en su etiqueta.
    */
    private void lblFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFiltroMouseClicked
        txtFiltro.requestFocus();
    }//GEN-LAST:event_lblFiltroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBorrarFiltro;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnPosterior;
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JFormattedTextField ftxtVotos;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblGuia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblVotos;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
