package vista;

import modelo.Partido;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import servicios.PartidoService;

public class PanelFormulario3 extends javax.swing.JPanel {
    
    DefaultComboBoxModel<Partido> model;
    
    public PanelFormulario3() {
        initComponents();
        cargarLista();
    }
    
    /**
    * Carga la lista de partidos en el combo box, agregando una opción
    * inicial "(Seleccionar)" como primer elemento para forzar una elección.
    */
    private void cargarLista(){
        model = new DefaultComboBoxModel<>();
        model.addElement(new Partido(0, "(Seleccionar)", 0)); // opción vacía por defecto
        for (Partido p : PartidoService.obtenerPartidos()) {
            model.addElement(p);
        }
        cbxPartidos.setModel(model);
    }
    
    /**
    * Sobrescribe setVisible para recargar la lista de partidos cada vez
    * que el panel se hace visible, reflejando cambios recientes.
    */
    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag) {
            cargarLista();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeleccionar = new javax.swing.JLabel();
        cbxPartidos = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();

        lblSeleccionar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSeleccionar.setText("Seleccionar partido");

        cbxPartidos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAceptar.setText("Dar de baja");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeleccionar)
                    .addComponent(cbxPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccionar)
                    .addComponent(btnAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    * Solicita confirmación y elimina el partido seleccionado en el combo box.
    * Si no hay partido seleccionado, muestra un aviso. Si el usuario confirma
    * la eliminación, borra el registro y recarga la lista.
    */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // Índice 0 corresponde a la opción "(Seleccionar)"
        if (cbxPartidos.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "No hay un partido seleccionado", "", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String[] opcs = {"Eliminar", "Volver"};
        
        int resp = JOptionPane.showOptionDialog(null,
            "¿Está seguro de eliminar este partido?", "",
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
            opcs,
            opcs[1]); // "Volver" es la opción por defecto
        
        if (resp == 0) { // el usuario eligió "Eliminar"
            int id = ((Partido) cbxPartidos.getSelectedItem()).getId();
            PartidoService.eliminarPartido(id);
            JOptionPane.showMessageDialog(null,"Eliminado");
            cargarLista(); // recarga el combo box sin el partido eliminado
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<Partido> cbxPartidos;
    private javax.swing.JLabel lblSeleccionar;
    // End of variables declaration//GEN-END:variables
}
