package sistemadhondt;

import java.awt.CardLayout;

public class MainB extends javax.swing.JFrame {

    
    CardLayout cl;
    public MainB() {
        initComponents();
        pnlPrincipal.setLayout(new CardLayout());
        cl = (CardLayout)(pnlPrincipal.getLayout());
        pnlPrincipal.add(new PanelFormulario1(), "crear");
        pnlPrincipal.add(new PanelFormulario2(), "modificar");
        pnlPrincipal.add(new PanelFormulario3(), "eliminar");
        pnlPrincipal.add(new PanelFormulario4(), "informe-cargos");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        mnArchivos = new javax.swing.JMenu();
        mnitCrear = new javax.swing.JMenuItem();
        mnitEliminar = new javax.swing.JMenuItem();
        sprSeparador = new javax.swing.JPopupMenu.Separator();
        mnitSalir = new javax.swing.JMenuItem();
        mnEditar = new javax.swing.JMenu();
        mnitModificar = new javax.swing.JMenuItem();
        mnInformes = new javax.swing.JMenu();
        mnitInformeCargos = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        menuBar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        mnArchivos.setText("Archivos");
        mnArchivos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        mnitCrear.setText("Cargar partido");
        mnitCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitCrearActionPerformed(evt);
            }
        });
        mnArchivos.add(mnitCrear);

        mnitEliminar.setText("Eliminar partido");
        mnitEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitEliminarActionPerformed(evt);
            }
        });
        mnArchivos.add(mnitEliminar);
        mnArchivos.add(sprSeparador);

        mnitSalir.setText("Salir");
        mnitSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitSalirActionPerformed(evt);
            }
        });
        mnArchivos.add(mnitSalir);

        menuBar.add(mnArchivos);

        mnEditar.setText("Editar");
        mnEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        mnitModificar.setText("Modificar partido");
        mnitModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitModificarActionPerformed(evt);
            }
        });
        mnEditar.add(mnitModificar);

        menuBar.add(mnEditar);

        mnInformes.setText("Informes");
        mnInformes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        mnitInformeCargos.setText("Cargos a cubrir");
        mnitInformeCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitInformeCargosActionPerformed(evt);
            }
        });
        mnInformes.add(mnitInformeCargos);

        menuBar.add(mnInformes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnitCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitCrearActionPerformed
        cl.show(pnlPrincipal, "crear");
    }//GEN-LAST:event_mnitCrearActionPerformed

    private void mnitEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitEliminarActionPerformed
        cl.show(pnlPrincipal, "eliminar");
    }//GEN-LAST:event_mnitEliminarActionPerformed

    private void mnitModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitModificarActionPerformed
        cl.show(pnlPrincipal, "modificar");
    }//GEN-LAST:event_mnitModificarActionPerformed

    private void mnitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnitSalirActionPerformed

    private void mnitInformeCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitInformeCargosActionPerformed
        cl.show(pnlPrincipal, "informe-cargos");
    }//GEN-LAST:event_mnitInformeCargosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainB().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnArchivos;
    private javax.swing.JMenu mnEditar;
    private javax.swing.JMenu mnInformes;
    private javax.swing.JMenuItem mnitCrear;
    private javax.swing.JMenuItem mnitEliminar;
    private javax.swing.JMenuItem mnitInformeCargos;
    private javax.swing.JMenuItem mnitModificar;
    private javax.swing.JMenuItem mnitSalir;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPopupMenu.Separator sprSeparador;
    // End of variables declaration//GEN-END:variables
}
