package sistemadhondt;

import java.awt.HeadlessException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class PanelFormulario2 extends javax.swing.JPanel {

    private List<Partido> lista, partidos, partidosFiltro;
    private int indice = 0;
    private int id;
    boolean filtro;
    
    public PanelFormulario2() {
        initComponents();
        cargarDatosIniciales();
    }
    
    private void cargarDatosIniciales() {
        partidos = ConexionDAO.mostrarPartidos();
        indice = 0;

        if (partidos != null && !partidos.isEmpty()) {
            lblMensaje.setText("");
            mostrarActual();
        } else {
            txtNombre.setText("");
            ftxtVotos.setValue(0L);
            lblGuia.setText("0 / 0");
            lblMensaje.setText("No hay partidos registrados");
        }
    }
    
    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag) {
            cargarDatosIniciales();
        }
    }
    
    private void mostrarActual() {
        lista = filtro ? partidosFiltro : partidos;

        if (lista == null || lista.isEmpty()) return;

        Partido p = lista.get(indice);
        this.id = p.getId();
        
        this.txtNombre.setText(p.getNombre());
        ftxtVotos.setValue((long) p.getVotos());

        lblGuia.setText((indice + 1) + " / " + lista.size());
    }
    
    
    private void actualizarPartidoActual() {
        lista = filtro ? partidosFiltro : partidos;

        if (lista == null || lista.isEmpty()) return;

        try {
            Partido p = lista.get(indice);
            String nuevoNombre = txtNombre.getText();
            
            ftxtVotos.commitEdit();
            long nuevosVotos = ftxtVotos.getValue() != null ? (Long) ftxtVotos.getValue() : 0L;
            
            if (nuevoNombre.isEmpty()) return;
            
            ConexionDAO.actualizarPartido(p.getId(), nuevoNombre, (int)nuevosVotos);

            
            partidos.set(indice, new Partido(p.getId(), nuevoNombre, (int)nuevosVotos));

        } catch (NumberFormatException e) {
            System.out.println("Error en votos, número no válido.");
            JOptionPane.showMessageDialog(null, "No puede haber casillas vacías.", "", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException e) {
            System.out.println("Error en votos, número no válido.");
            //
        }
    }
    
    private void actualizarRegistro(java.awt.event.KeyEvent evt){
        try {
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                actualizarPartidoActual();
                JOptionPane.showMessageDialog(null,"Actualizado");
            }
            
        } catch (HeadlessException ex){
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblVotos = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        btnPosterior = new javax.swing.JButton();
        btnFin = new javax.swing.JButton();
        btnPrincipio = new javax.swing.JButton();
        lblGuia = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        ftxtVotos = new javax.swing.JFormattedTextField();

        lblNombre.setText("Nombre del partido");

        lblVotos.setText("Cantidad de votos");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnPosterior.setText(">");
        btnPosterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosteriorActionPerformed(evt);
            }
        });

        btnFin.setText(">|");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });

        btnPrincipio.setText("|<");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });

        lblGuia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuia.setText("0/0");

        txtFiltro.setText("Filtro");
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        ftxtVotos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        ftxtVotos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtVotosActionPerformed(evt);
            }
        });
        ftxtVotos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftxtVotosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxtVotosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblVotos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(ftxtVotos)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPrincipio, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGuia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPosterior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVotos)
                    .addComponent(ftxtVotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnPosterior)
                    .addComponent(btnFin)
                    .addComponent(btnPrincipio)
                    .addComponent(lblGuia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensaje))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        indice--;
        if (indice < 0) {
            indice++;
        }
        mostrarActual();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        indice = 0;
        mostrarActual();
    }//GEN-LAST:event_btnPrincipioActionPerformed

    private void btnPosteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosteriorActionPerformed
        indice++;
        if (indice >= lista.size()) {
            indice = lista.size()-1;
        }
        mostrarActual();
    }//GEN-LAST:event_btnPosteriorActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        indice = lista.size() - 1;
        mostrarActual();
    }//GEN-LAST:event_btnFinActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        partidosFiltro = new ArrayList<>();
        
        for (Partido p : partidos) {
            boolean coincideNombre = p.getNombre().toLowerCase().contains(txtFiltro.getText().toLowerCase());
            boolean coincideVotos = String.valueOf(p.getVotos()).contains(txtFiltro.getText());
            if (coincideNombre || coincideVotos) {
                partidosFiltro.add(p);
            }
        }
        
        if(txtFiltro.getText().equals("")){
            filtro = false;
        } else {
            filtro = true;
            indice = 0;
        }

        if (!partidosFiltro.isEmpty()) {
            mostrarActual();
        } else {
            txtNombre.setText("");
            ftxtVotos.setText("");
            lblGuia.setText("0 / 0");
        }
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void ftxtVotosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtVotosKeyPressed
        actualizarRegistro(evt);
    }//GEN-LAST:event_ftxtVotosKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        actualizarRegistro(evt);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void ftxtVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtVotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtVotosActionPerformed

    private void ftxtVotosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtVotosKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_ftxtVotosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnPosterior;
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JFormattedTextField ftxtVotos;
    private javax.swing.JLabel lblGuia;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblVotos;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
