package sistemadhondt;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class PanelFormulario3 extends javax.swing.JPanel {
    
    DefaultComboBoxModel<Partido> model;
    
    public PanelFormulario3() {
        initComponents();
        cargarLista();
    }
    
    private void cargarLista(){
        model = new DefaultComboBoxModel<>();
        List<Partido> partidos = ConexionDAO.mostrarPartidos();
        model.addElement(new Partido(0, "(Seleccionar)", 0));
        for (Partido p : partidos) {
            model.addElement(p);
        }
        cbxPartidos.setModel(model);
    }
    
    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag) {
            cargarLista();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeleccionar = new javax.swing.JLabel();
        cbxPartidos = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        lblSeleccionar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSeleccionar.setText("Seleccionar partido");

        cbxPartidos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbxPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPartidosActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAceptar.setText("Dar de baja");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeleccionar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxPartidos, javax.swing.GroupLayout.Alignment.LEADING, 0, 205, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccionar)
                    .addComponent(btnAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String[] opcs = {"Eliminar", "Volver"};
        
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lblMensaje.setText("");
            }
        });
        
        if (cbxPartidos.getSelectedIndex() != 0) {
            int resp = JOptionPane.showOptionDialog(null,
                "�Est� seguro de eliminar este partido?", "",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                opcs,
                opcs[1]);
        
            if (resp == 0) {
                // Se presion� "Eliminar"
                int id = ((Partido) cbxPartidos.getSelectedItem()).getId();
                ConexionDAO.eliminarPartido(id);
                JOptionPane.showMessageDialog(null,"Eliminado");
                cargarLista();
            }
        } else {
            lblMensaje.setText("Elija un partido a eliminar.");
            timer.setRepeats(false);
            timer.start();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cbxPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPartidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPartidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<Partido> cbxPartidos;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblSeleccionar;
    // End of variables declaration//GEN-END:variables
}
