package sistemadhondt;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class PanelFormulario4 extends javax.swing.JPanel {
    
    //private PanelInformeCargos panelInforme;
    javax.swing.JPanel pnlInforme;
    
    DefaultComboBoxModel model;
    public PanelFormulario4() {
        initComponents();
        cargarDatosIniciales();
        //panelInforme = new PanelInformeCargos();
    }
    
    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag) {
            cargarDatosIniciales();
        }
    }
    
    private void cargarDatosIniciales(){
        model = new DefaultComboBoxModel();
        for (int i=1; i <= 100; i++){
            model.addElement(i+"%");
        }
        
        cbxPorcentaje.setModel(model);
        ftxtCargos.setText("");
    }
            
    protected List<Partido> filtrarPartidos(List<Partido> partidos){
        int totalVotos = 0;
        
        String seleccion = cbxPorcentaje.getSelectedItem().toString().replace("%", "");
        double porcentaje = Double.parseDouble(seleccion) / 100.0;
        
        for (Partido p : partidos) {
            totalVotos += p.getVotos();
        }
        
        if (totalVotos == 0) return new ArrayList<>();
        
        List<Partido> filtrados = new ArrayList<>();
        
        for (Partido p : partidos) {
            
            double porcentajePartido = p.getVotos() / (double) totalVotos;

            if (porcentajePartido >= porcentaje) {
                filtrados.add(p);
            }
            
            System.out.println("\n=== PORCENTAJES ===");
            System.out.printf("%-15s %8.2f%%%n", p.getNombre(), porcentajePartido * 100);
            
        }
        
        System.out.println("\n=== PARTIDOS QUE PASAN EL FILTRO ===");
        System.out.println(filtrados);
        
        
        return filtrados;
    }
    
    protected void irAlInforme(){
        try {
            java.io.InputStream jrxml = getClass().getResourceAsStream("/informes/report1.jrxml");
            net.sf.jasperreports.engine.JasperReport jasperReport =
                net.sf.jasperreports.engine.JasperCompileManager.compileReport(jrxml);
            java.util.Map<String, Object> parametros = new java.util.HashMap<>();
            
            JasperPrint jasperPrint =
                JasperFillManager.fillReport(
                    jasperReport,
                    parametros,
                    Conexion.conectar()
                );
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Throwable cause = ex.getCause();
            while (cause != null) {
                System.out.println("Causa: " + cause.getMessage());
                cause = cause.getCause();
            }
            JOptionPane.showMessageDialog(null, "Error al generar el informe: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantidadCargos = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        cbxPorcentaje = new javax.swing.JComboBox<>();
        lblPorcentaje = new javax.swing.JLabel();
        ftxtCargos = new javax.swing.JFormattedTextField();

        lblCantidadCargos.setText("Cantidad de cargos a cubrir");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblPorcentaje.setText("Indique porcentaje");

        ftxtCargos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        ftxtCargos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftxtCargos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxtCargosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCantidadCargos)
                            .addComponent(ftxtCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPorcentaje)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cbxPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadCargos)
                    .addComponent(lblPorcentaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        List<Partido> todosLosPartidos = ConexionDAO.mostrarPartidos();
        int totalVotos = todosLosPartidos.stream().mapToInt(Partido::getVotos).sum();
       
        List<Partido> partidos = filtrarPartidos(todosLosPartidos);

        if (partidos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay partidos cargados.");
            return;
        }

        String cargosPrev = ftxtCargos.getText();
        if (cargosPrev.isEmpty() || cargosPrev.equals("0")) {
            JOptionPane.showMessageDialog(null, "No se asignó una cantidad de cargos.");
            return;
        }

        int cargos = Integer.parseInt(cargosPrev);

        // Armar cocientes
        List<ResultadoVotos> cocientes = new ArrayList<>();
        for (Partido p : partidos) {
            for (int i = 1; i <= cargos; i++) {
                ResultadoVotos r = new ResultadoVotos(
                    p.getId(),
                    p.getVotos() / i,
                    0,  // orden se asigna después
                    i,
                    (p.getVotos() / (double) totalVotos) * 100,
                    totalVotos
                );
                cocientes.add(r);
            }
        }

        // Ordenar por cociente
        cocientes.sort((a, b) -> Integer.compare(b.getCantidadVotos(), a.getCantidadVotos()));

        // Asignar orden y quedarse solo con los primeros N
        List<ResultadoVotos> resultados = new ArrayList<>();
        for (int i = 0; i < Math.min(cargos, cocientes.size()); i++) {
            ResultadoVotos r = cocientes.get(i);
            r.setOrden(i + 1);
            resultados.add(r);
        }

        // Guardar en la base de datos
        ConexionDAO.insertarResultados(resultados);

        // Navegar al informe
        irAlInforme();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void ftxtCargosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtCargosKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_ftxtCargosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cbxPorcentaje;
    private javax.swing.JFormattedTextField ftxtCargos;
    private javax.swing.JLabel lblCantidadCargos;
    private javax.swing.JLabel lblPorcentaje;
    // End of variables declaration//GEN-END:variables
}
